name: sviitest
favicon: null
layout_spectrum: 0.68405
typography_spectrum: 0.229441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B0A890'
    - '#781818'
    - '#A89878'
    - '#5080C8'
    - '#80A8D8'
  brandStrength: 0.675987
  lightness: 0.144271
  saturation: 0.412663
  rhythmicContrast: 0.164837
purpose:
  - name: null
    item: null
    url: null
